parameters: {}
environment: {}

packages:
  - name: shared
    functions:
      - name: shared
        runtime: nodejs:18
        source_dir: shared/src

  - name: evals
    functions:
      - name: evals
        runtime: nodejs:18
        source_dir: evals/src
        ignore:
          - "**/*.prettierrc"
          - "**/*.eslintrc.*"
          - "**/*.tsconfig*"
          - "**/turbo"
