[services.langgraphserver]
name = "LangGraphServer"
build.command = "cd apps/agents && yarn install && yarn build"
start.command = "cd apps/agents && npx @langchain/langgraph-cli dev --port 54367 --config ../../langgraph.json"

[services.langgraphserver.env]
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "AIR-SafeIT-journalhelper-v0.2"
OPENAI_API_KEY = "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"
NEXT_PUBLIC_SUPABASE_URL = "https://byeoqfrjhsnrdwfmegem.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZW9xZnJqaHNucmR3Zm1lZ2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTEwOTMsImV4cCI6MjA1ODI2NzA5M30.OxaMjTNPfpYcE9CUFg4ljPxkK0XO64RORy6GUXHVbtU"
SUPABASE_SERVICE_ROLE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZW9xZnJqaHNucmR3Zm1lZ2VtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjY5MTA5MywiZXhwIjoyMDU4MjY3MDkzfQ.YpBtdpB6k7pfF4go58pY3prIkLTd1pYbRyA5WGL7_94"

[services.frontend]
name = "Frontend"
build.command = "cd apps/web && yarn install && yarn build"
start.command = "cd apps/web && next start"

[services.frontend.env]
NEXT_PUBLIC_FIREWORKS_ENABLED = "false"
NEXT_PUBLIC_GEMINI_ENABLED = "false"
NEXT_PUBLIC_ANTHROPIC_ENABLED = "false"
NEXT_PUBLIC_OPENAI_ENABLED = "true"
NEXT_PUBLIC_AZURE_ENABLED = "false"
NEXT_PUBLIC_OLLAMA_ENABLED = "false"
NEXT_PUBLIC_GROQ_ENABLED = "false"
NEXT_PUBLIC_SUPABASE_URL = "https://byeoqfrjhsnrdwfmegem.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZW9xZnJqaHNucmR3Zm1lZ2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTEwOTMsImV4cCI6MjA1ODI2NzA5M30.OxaMjTNPfpYcE9CUFg4ljPxkK0XO64RORy6GUXHVbtU"
NEXT_PUBLIC_SUPABASE_URL_DOCUMENTS = "https://byeoqfrjhsnrdwfmegem.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY_DOCUMENTS = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZW9xZnJqaHNucmR3Zm1lZ2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTEwOTMsImV4cCI6MjA1ODI2NzA5M30.OxaMjTNPfpYcE9CUFg4ljPxkK0XO64RORy6GUXHVbtU"
